language: go

env:
 - GO111MODULE=on
 
branches:
  only:
  - master
  - develop
  - dev-oidc

install:
 - go mod download

script:
 - go vet ./...
 - diff <(goimports -d .) <(printf "")
 - diff <(golint ./...) <(printf "")